#!/usr/bin/env python3
"""Generate Rust source files for Lucide icons.

Reads all SVGs from references/lucide/icons/ and produces:
  - src/icons/lucide_icon.rs   (enum with one variant per icon)
  - src/icons/lucide_icon_data.rs (svg_data() returning inner SVG XML)
"""

import glob
import os
import re
import sys


def kebab_to_pascal(name: str) -> str:
    """Convert kebab-case filename stem to PascalCase variant name."""
    return "".join(part.capitalize() for part in name.split("-"))


def extract_inner_svg(svg_text: str) -> str:
    """Strip the outer <svg ...> wrapper and return inner elements."""
    # Remove the opening <svg ...> tag
    inner = re.sub(r"<svg[^>]*>", "", svg_text, count=1)
    # Remove the closing </svg> tag
    inner = re.sub(r"</svg>\s*$", "", inner)
    # Collapse whitespace / newlines to single spaces
    inner = re.sub(r"\s+", " ", inner).strip()
    return inner


def main() -> None:
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    icons_dir = os.path.join(project_root, "references", "lucide", "icons")
    out_dir = os.path.join(project_root, "src", "icons")

    svg_files = sorted(glob.glob(os.path.join(icons_dir, "*.svg")))
    if not svg_files:
        print(f"No SVG files found in {icons_dir}", file=sys.stderr)
        sys.exit(1)

    # Collect (kebab_name, PascalName, inner_svg) tuples
    icons: list[tuple[str, str, str]] = []
    for path in svg_files:
        stem = os.path.splitext(os.path.basename(path))[0]
        pascal = kebab_to_pascal(stem)
        with open(path, "r") as f:
            inner = extract_inner_svg(f.read())
        icons.append((stem, pascal, inner))

    print(f"Found {len(icons)} icons")

    # ── lucide_icon.rs ──────────────────────────────────────────────
    with open(os.path.join(out_dir, "lucide_icon.rs"), "w") as f:
        f.write("//! Auto-generated Lucide icon enum.\n")
        f.write("//!\n")
        f.write(f"//! {len(icons)} variants, generated by scripts/generate_icons.py.\n")
        f.write("//! Do not edit by hand.\n\n")
        f.write("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n")
        f.write("pub enum LucideIcon {\n")
        for _, pascal, _ in icons:
            f.write(f"    {pascal},\n")
        f.write("}\n\n")
        f.write(f"/// All {len(icons)} icon variants in alphabetical order.\n")
        f.write(f"pub const ALL: &[LucideIcon] = &[\n")
        for _, pascal, _ in icons:
            f.write(f"    LucideIcon::{pascal},\n")
        f.write("];\n\n")
        f.write("impl LucideIcon {\n")
        f.write("    /// Returns the kebab-case name of this icon.\n")
        f.write("    pub fn name(&self) -> &'static str {\n")
        f.write("        match self {\n")
        for kebab, pascal, _ in icons:
            f.write(f'            LucideIcon::{pascal} => "{kebab}",\n')
        f.write("        }\n")
        f.write("    }\n")
        f.write("}\n")

    # ── lucide_icon_data.rs ─────────────────────────────────────────
    with open(os.path.join(out_dir, "lucide_icon_data.rs"), "w") as f:
        f.write("//! Auto-generated SVG data for each Lucide icon.\n")
        f.write("//!\n")
        f.write(f"//! {len(icons)} entries, generated by scripts/generate_icons.py.\n")
        f.write("//! Do not edit by hand.\n\n")
        f.write("impl super::lucide_icon::LucideIcon {\n")
        f.write("    /// Returns the inner SVG XML (elements inside the `<svg>` wrapper).\n")
        f.write("    pub fn svg_data(&self) -> &'static str {\n")
        f.write("        match self {\n")
        for _, pascal, inner in icons:
            # Escape backslashes and double-quotes in the SVG data
            escaped = inner.replace("\\", "\\\\").replace('"', '\\"')
            f.write(
                f'            super::lucide_icon::LucideIcon::{pascal} => "{escaped}",\n'
            )
        f.write("        }\n")
        f.write("    }\n")
        f.write("}\n")

    print(f"Generated lucide_icon.rs and lucide_icon_data.rs ({len(icons)} icons)")


if __name__ == "__main__":
    main()
